"""Add brands table with proper model

Revision ID: 9ec3e1a15249
Revises: ea65b5eb8a45
Create Date: 2025-08-21 01:20:46.350994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ec3e1a15249'
down_revision: Union[str, None] = 'ea65b5eb8a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Brand name'),
    sa.Column('code', sa.String(length=20), nullable=True, comment='Unique brand code'),
    sa.Column('description', sa.Text(), nullable=True, comment='Brand description'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='UUID primary key generated by PostgreSQL'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_brand_code_active', 'brands', ['code', 'is_active'], unique=False)
    op.create_index('idx_brand_name_active', 'brands', ['name', 'is_active'], unique=False)
    op.create_index(op.f('ix_brands_code'), 'brands', ['code'], unique=True)
    op.create_index(op.f('ix_brands_is_active'), 'brands', ['is_active'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_is_active'), table_name='brands')
    op.drop_index(op.f('ix_brands_code'), table_name='brands')
    op.drop_index('idx_brand_name_active', table_name='brands')
    op.drop_index('idx_brand_code_active', table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###