"""Add company table

Revision ID: fc52e016b839
Revises: df3e077752cb
Create Date: 2025-08-21 00:25:55.584303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc52e016b839'
down_revision: Union[str, None] = 'df3e077752cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_name', sa.String(length=255), nullable=False, comment='Company name'),
    sa.Column('address', sa.Text(), nullable=True, comment='Company address'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Company email'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='Company phone number'),
    sa.Column('gst_no', sa.String(length=50), nullable=True, comment='GST registration number'),
    sa.Column('registration_number', sa.String(length=100), nullable=True, comment='Company registration number'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='UUID primary key generated by PostgreSQL'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_company_name_active', 'companies', ['company_name', 'is_active'], unique=False)
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=True)
    op.create_index(op.f('ix_companies_gst_no'), 'companies', ['gst_no'], unique=True)
    op.create_index(op.f('ix_companies_is_active'), 'companies', ['is_active'], unique=False)
    op.create_index(op.f('ix_companies_registration_number'), 'companies', ['registration_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_registration_number'), table_name='companies')
    op.drop_index(op.f('ix_companies_is_active'), table_name='companies')
    op.drop_index(op.f('ix_companies_gst_no'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.drop_index('idx_company_name_active', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###