"""Add locations table with spatial indexes and hierarchy support

Revision ID: 039eaa19ce66
Revises: 080519bf1831
Create Date: 2025-08-21 12:52:08.808635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '039eaa19ce66'
down_revision: Union[str, None] = '080519bf1831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_of_measurements',
    sa.Column('name', sa.String(length=50), nullable=False, comment='Unit name'),
    sa.Column('code', sa.String(length=10), nullable=True, comment='Unit code/abbreviation'),
    sa.Column('description', sa.Text(), nullable=True, comment='Unit description'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='UUID primary key generated by PostgreSQL'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_uom_code_active', 'unit_of_measurements', ['code', 'is_active'], unique=False)
    op.create_index('idx_uom_created_at', 'unit_of_measurements', ['created_at'], unique=False)
    op.create_index('idx_uom_name_active', 'unit_of_measurements', ['name', 'is_active'], unique=False)
    op.create_index(op.f('ix_unit_of_measurements_code'), 'unit_of_measurements', ['code'], unique=True)
    op.create_index(op.f('ix_unit_of_measurements_is_active'), 'unit_of_measurements', ['is_active'], unique=False)
    op.create_index(op.f('ix_unit_of_measurements_name'), 'unit_of_measurements', ['name'], unique=True)
    op.create_table('items',
    sa.Column('item_name', sa.String(length=255), nullable=False, comment='Name of the item'),
    sa.Column('sku', sa.String(length=50), nullable=False, comment='Stock Keeping Unit (auto-generated)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of the item'),
    sa.Column('short_description', sa.String(length=500), nullable=True, comment='Brief description for listings'),
    sa.Column('brand_id', sa.UUID(), nullable=True, comment='Brand ID'),
    sa.Column('category_id', sa.UUID(), nullable=True, comment='Category ID'),
    sa.Column('unit_of_measurement_id', sa.UUID(), nullable=True, comment='Unit of measurement ID'),
    sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=True, comment='Weight in kg'),
    sa.Column('dimensions_length', sa.Numeric(precision=10, scale=2), nullable=True, comment='Length in cm'),
    sa.Column('dimensions_width', sa.Numeric(precision=10, scale=2), nullable=True, comment='Width in cm'),
    sa.Column('dimensions_height', sa.Numeric(precision=10, scale=2), nullable=True, comment='Height in cm'),
    sa.Column('color', sa.String(length=50), nullable=True, comment='Item color'),
    sa.Column('material', sa.String(length=100), nullable=True, comment='Material composition'),
    sa.Column('is_rentable', sa.Boolean(), nullable=False, comment='Whether item can be rented'),
    sa.Column('is_salable', sa.Boolean(), nullable=False, comment='Whether item can be sold'),
    sa.Column('requires_serial_number', sa.Boolean(), nullable=False, comment='Whether serial numbers are required'),
    sa.Column('cost_price', sa.Numeric(precision=15, scale=2), nullable=True, comment='Cost to acquire the item'),
    sa.Column('sale_price', sa.Numeric(precision=15, scale=2), nullable=True, comment='Selling price'),
    sa.Column('rental_rate_per_day', sa.Numeric(precision=15, scale=2), nullable=True, comment='Daily rental rate'),
    sa.Column('security_deposit', sa.Numeric(precision=15, scale=2), nullable=True, comment='Required deposit for rentals'),
    sa.Column('is_rental_blocked', sa.Boolean(), nullable=False, comment='Whether rental is currently blocked'),
    sa.Column('rental_block_reason', sa.String(length=500), nullable=True, comment='Reason for blocking rental'),
    sa.Column('rental_blocked_at', sa.DateTime(timezone=True), nullable=True, comment='When rental was blocked'),
    sa.Column('rental_blocked_by', sa.UUID(), nullable=True, comment='UUID of user who blocked rental'),
    sa.Column('reorder_level', sa.Integer(), nullable=True, comment='Minimum stock level before reordering'),
    sa.Column('maximum_stock_level', sa.Integer(), nullable=True, comment='Maximum stock level'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Current item status'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes about the item'),
    sa.Column('tags', sa.String(length=1000), nullable=True, comment='Comma-separated tags for search'),
    sa.Column('last_maintenance_date', sa.DateTime(timezone=True), nullable=True, comment='Last maintenance performed'),
    sa.Column('warranty_expiry_date', sa.DateTime(timezone=True), nullable=True, comment='Warranty expiration date'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='UUID primary key generated by PostgreSQL'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['unit_of_measurement_id'], ['unit_of_measurements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_item_brand_active', 'items', ['brand_id', 'is_active'], unique=False)
    op.create_index('idx_item_brand_salable', 'items', ['brand_id', 'is_salable', 'is_active'], unique=False)
    op.create_index('idx_item_category_active', 'items', ['category_id', 'is_active'], unique=False)
    op.create_index('idx_item_category_rentable', 'items', ['category_id', 'is_rentable', 'is_active'], unique=False)
    op.create_index('idx_item_name_active', 'items', ['item_name', 'is_active'], unique=False)
    op.create_index('idx_item_rentable_active', 'items', ['is_rentable', 'is_active'], unique=False)
    op.create_index('idx_item_rental_blocked', 'items', ['is_rental_blocked', 'is_active'], unique=False)
    op.create_index('idx_item_rental_rate', 'items', ['rental_rate_per_day'], unique=False)
    op.create_index('idx_item_salable_active', 'items', ['is_salable', 'is_active'], unique=False)
    op.create_index('idx_item_sale_price', 'items', ['sale_price'], unique=False)
    op.create_index('idx_item_search_text', 'items', ['item_name', 'short_description'], unique=False)
    op.create_index('idx_item_sku_active', 'items', ['sku', 'is_active'], unique=False)
    op.create_index('idx_item_status_active', 'items', ['status', 'is_active'], unique=False)
    op.create_index('idx_item_unit_active', 'items', ['unit_of_measurement_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_items_brand_id'), 'items', ['brand_id'], unique=False)
    op.create_index(op.f('ix_items_category_id'), 'items', ['category_id'], unique=False)
    op.create_index(op.f('ix_items_is_active'), 'items', ['is_active'], unique=False)
    op.create_index(op.f('ix_items_is_rentable'), 'items', ['is_rentable'], unique=False)
    op.create_index(op.f('ix_items_is_rental_blocked'), 'items', ['is_rental_blocked'], unique=False)
    op.create_index(op.f('ix_items_is_salable'), 'items', ['is_salable'], unique=False)
    op.create_index(op.f('ix_items_item_name'), 'items', ['item_name'], unique=False)
    op.create_index(op.f('ix_items_sku'), 'items', ['sku'], unique=True)
    op.create_index(op.f('ix_items_status'), 'items', ['status'], unique=False)
    op.create_index(op.f('ix_items_unit_of_measurement_id'), 'items', ['unit_of_measurement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_unit_of_measurement_id'), table_name='items')
    op.drop_index(op.f('ix_items_status'), table_name='items')
    op.drop_index(op.f('ix_items_sku'), table_name='items')
    op.drop_index(op.f('ix_items_item_name'), table_name='items')
    op.drop_index(op.f('ix_items_is_salable'), table_name='items')
    op.drop_index(op.f('ix_items_is_rental_blocked'), table_name='items')
    op.drop_index(op.f('ix_items_is_rentable'), table_name='items')
    op.drop_index(op.f('ix_items_is_active'), table_name='items')
    op.drop_index(op.f('ix_items_category_id'), table_name='items')
    op.drop_index(op.f('ix_items_brand_id'), table_name='items')
    op.drop_index('idx_item_unit_active', table_name='items')
    op.drop_index('idx_item_status_active', table_name='items')
    op.drop_index('idx_item_sku_active', table_name='items')
    op.drop_index('idx_item_search_text', table_name='items')
    op.drop_index('idx_item_sale_price', table_name='items')
    op.drop_index('idx_item_salable_active', table_name='items')
    op.drop_index('idx_item_rental_rate', table_name='items')
    op.drop_index('idx_item_rental_blocked', table_name='items')
    op.drop_index('idx_item_rentable_active', table_name='items')
    op.drop_index('idx_item_name_active', table_name='items')
    op.drop_index('idx_item_category_rentable', table_name='items')
    op.drop_index('idx_item_category_active', table_name='items')
    op.drop_index('idx_item_brand_salable', table_name='items')
    op.drop_index('idx_item_brand_active', table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_unit_of_measurements_name'), table_name='unit_of_measurements')
    op.drop_index(op.f('ix_unit_of_measurements_is_active'), table_name='unit_of_measurements')
    op.drop_index(op.f('ix_unit_of_measurements_code'), table_name='unit_of_measurements')
    op.drop_index('idx_uom_name_active', table_name='unit_of_measurements')
    op.drop_index('idx_uom_created_at', table_name='unit_of_measurements')
    op.drop_index('idx_uom_code_active', table_name='unit_of_measurements')
    op.drop_table('unit_of_measurements')
    # ### end Alembic commands ###