"""Add supplier table

Revision ID: df3e077752cb
Revises: ee32a1d18bce
Create Date: 2025-08-20 22:18:57.649775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df3e077752cb'
down_revision: Union[str, None] = 'ee32a1d18bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('supplier_code', sa.String(length=50), nullable=False, comment='Unique supplier code'),
    sa.Column('company_name', sa.String(length=255), nullable=False, comment='Supplier company name'),
    sa.Column('supplier_type', sa.String(length=20), nullable=False, comment='Type of supplier'),
    sa.Column('contact_person', sa.String(length=255), nullable=True, comment='Primary contact person'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Supplier email address'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='Supplier phone number'),
    sa.Column('mobile', sa.String(length=50), nullable=True, comment='Supplier mobile number'),
    sa.Column('address_line1', sa.String(length=255), nullable=True, comment='Primary address line'),
    sa.Column('address_line2', sa.String(length=255), nullable=True, comment='Secondary address line'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='City'),
    sa.Column('state', sa.String(length=100), nullable=True, comment='State/Province'),
    sa.Column('postal_code', sa.String(length=20), nullable=True, comment='Postal/ZIP code'),
    sa.Column('country', sa.String(length=100), nullable=True, comment='Country'),
    sa.Column('tax_id', sa.String(length=50), nullable=True, comment='Tax identification number'),
    sa.Column('payment_terms', sa.String(length=20), nullable=False, comment='Payment terms'),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=False, comment='Credit limit amount'),
    sa.Column('supplier_tier', sa.String(length=20), nullable=False, comment='Supplier tier'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Supplier status'),
    sa.Column('quality_rating', sa.Numeric(precision=3, scale=2), nullable=False, comment='Quality rating (0-5)'),
    sa.Column('delivery_rating', sa.Numeric(precision=3, scale=2), nullable=False, comment='Delivery rating (0-5)'),
    sa.Column('average_delivery_days', sa.Integer(), nullable=False, comment='Average delivery time in days'),
    sa.Column('total_orders', sa.Integer(), nullable=False, comment='Total number of orders'),
    sa.Column('total_spend', sa.Numeric(precision=15, scale=2), nullable=False, comment='Total amount spent'),
    sa.Column('last_order_date', sa.DateTime(), nullable=True, comment='Date of last order'),
    sa.Column('contract_start_date', sa.DateTime(), nullable=True, comment='Contract start date'),
    sa.Column('contract_end_date', sa.DateTime(), nullable=True, comment='Contract end date'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes'),
    sa.Column('website', sa.String(length=255), nullable=True, comment='Supplier website'),
    sa.Column('account_manager', sa.String(length=255), nullable=True, comment='Account manager name'),
    sa.Column('preferred_payment_method', sa.String(length=50), nullable=True, comment='Preferred payment method'),
    sa.Column('insurance_expiry', sa.DateTime(), nullable=True, comment='Insurance expiry date'),
    sa.Column('certifications', sa.Text(), nullable=True, comment='Certifications held'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='UUID primary key generated by PostgreSQL'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.CheckConstraint("payment_terms IN ('IMMEDIATE', 'NET15', 'NET30', 'NET45', 'NET60', 'NET90', 'COD')", name='check_payment_terms'),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE', 'PENDING', 'APPROVED', 'SUSPENDED', 'BLACKLISTED')", name='check_supplier_status'),
    sa.CheckConstraint("supplier_tier IN ('PREMIUM', 'STANDARD', 'BASIC', 'TRIAL')", name='check_supplier_tier'),
    sa.CheckConstraint("supplier_type IN ('MANUFACTURER', 'DISTRIBUTOR', 'WHOLESALER', 'RETAILER', 'INVENTORY', 'SERVICE', 'DIRECT')", name='check_supplier_type'),
    sa.CheckConstraint('average_delivery_days >= 0', name='check_average_delivery_days'),
    sa.CheckConstraint('credit_limit >= 0', name='check_credit_limit'),
    sa.CheckConstraint('delivery_rating >= 0 AND delivery_rating <= 5', name='check_delivery_rating'),
    sa.CheckConstraint('quality_rating >= 0 AND quality_rating <= 5', name='check_quality_rating'),
    sa.CheckConstraint('total_orders >= 0', name='check_total_orders'),
    sa.CheckConstraint('total_spend >= 0', name='check_total_spend'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_supplier_code', 'suppliers', ['supplier_code'], unique=False)
    op.create_index('idx_supplier_company_name', 'suppliers', ['company_name'], unique=False)
    op.create_index('idx_supplier_contract_dates', 'suppliers', ['contract_start_date', 'contract_end_date'], unique=False)
    op.create_index('idx_supplier_email', 'suppliers', ['email'], unique=False)
    op.create_index('idx_supplier_last_order', 'suppliers', ['last_order_date'], unique=False)
    op.create_index('idx_supplier_payment_terms', 'suppliers', ['payment_terms'], unique=False)
    op.create_index('idx_supplier_ratings', 'suppliers', ['quality_rating', 'delivery_rating'], unique=False)
    op.create_index('idx_supplier_status', 'suppliers', ['status'], unique=False)
    op.create_index('idx_supplier_tier', 'suppliers', ['supplier_tier'], unique=False)
    op.create_index('idx_supplier_type', 'suppliers', ['supplier_type'], unique=False)
    op.create_index(op.f('ix_suppliers_company_name'), 'suppliers', ['company_name'], unique=False)
    op.create_index(op.f('ix_suppliers_email'), 'suppliers', ['email'], unique=False)
    op.create_index(op.f('ix_suppliers_is_active'), 'suppliers', ['is_active'], unique=False)
    op.create_index(op.f('ix_suppliers_supplier_code'), 'suppliers', ['supplier_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_supplier_code'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_is_active'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_email'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_company_name'), table_name='suppliers')
    op.drop_index('idx_supplier_type', table_name='suppliers')
    op.drop_index('idx_supplier_tier', table_name='suppliers')
    op.drop_index('idx_supplier_status', table_name='suppliers')
    op.drop_index('idx_supplier_ratings', table_name='suppliers')
    op.drop_index('idx_supplier_payment_terms', table_name='suppliers')
    op.drop_index('idx_supplier_last_order', table_name='suppliers')
    op.drop_index('idx_supplier_email', table_name='suppliers')
    op.drop_index('idx_supplier_contract_dates', table_name='suppliers')
    op.drop_index('idx_supplier_company_name', table_name='suppliers')
    op.drop_index('idx_supplier_code', table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###