"""add_contact_persons_table

Revision ID: b44b541c0e58
Revises: 9ec3e1a15249
Create Date: 2025-08-21 02:05:29.424843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b44b541c0e58'
down_revision: Union[str, None] = '9ec3e1a15249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_persons',
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='First name'),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment='Last name'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='Full name (computed)'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='Primary email address'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Primary phone number'),
    sa.Column('mobile', sa.String(length=20), nullable=True, comment='Mobile phone number'),
    sa.Column('title', sa.String(length=100), nullable=True, comment='Job title or position'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='Department or division'),
    sa.Column('company', sa.String(length=255), nullable=True, comment='Company name'),
    sa.Column('address', sa.Text(), nullable=True, comment='Street address'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='City'),
    sa.Column('state', sa.String(length=100), nullable=True, comment='State or province'),
    sa.Column('country', sa.String(length=100), nullable=True, comment='Country'),
    sa.Column('postal_code', sa.String(length=20), nullable=True, comment='Postal or ZIP code'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes or comments'),
    sa.Column('is_primary', sa.Boolean(), nullable=True, comment='Is this the primary contact'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='UUID primary key generated by PostgreSQL'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contact_person_company', 'contact_persons', ['company'], unique=False)
    op.create_index('idx_contact_person_email', 'contact_persons', ['email'], unique=False)
    op.create_index('idx_contact_person_full_name', 'contact_persons', ['full_name'], unique=False)
    op.create_index('idx_contact_person_location', 'contact_persons', ['city', 'state', 'country'], unique=False)
    op.create_index('idx_contact_person_mobile', 'contact_persons', ['mobile'], unique=False)
    op.create_index('idx_contact_person_phone', 'contact_persons', ['phone'], unique=False)
    op.create_index('idx_contact_person_primary', 'contact_persons', ['is_primary'], unique=False)
    op.create_index(op.f('ix_contact_persons_is_active'), 'contact_persons', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_persons_is_active'), table_name='contact_persons')
    op.drop_index('idx_contact_person_primary', table_name='contact_persons')
    op.drop_index('idx_contact_person_phone', table_name='contact_persons')
    op.drop_index('idx_contact_person_mobile', table_name='contact_persons')
    op.drop_index('idx_contact_person_location', table_name='contact_persons')
    op.drop_index('idx_contact_person_full_name', table_name='contact_persons')
    op.drop_index('idx_contact_person_email', table_name='contact_persons')
    op.drop_index('idx_contact_person_company', table_name='contact_persons')
    op.drop_table('contact_persons')
    # ### end Alembic commands ###